services:
  - type: web
    name: cloudnet
    env: go
    buildCommand: go build -o main
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false